import exception_handle as handle

if __name__=="__main__":
	# handle.throwException()
	# handle.throwExceptionfromPy()
	x = handle.X(23)